# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0bfec03474678493106de769a06a01d3b2172d81654e38bbc7bbcd06904f7bc632604017198e237791929ff537f0bd983f8dadedeea046895683e904622329

test:
  secret_key_base: 893000fd84980067f7f4dede19da35b464ef0c28257b1add8d593308be0d575f2e77a2eb091379f150af560f03a3d01811fb014775dc6a8c8790a314f4ae10da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
